### ISSUE TITLE
Version 0.1.3 in the description

### ISSUE THREAD

**Issue by oceanwp** [WPTRT/ns-theme-check#30]
Hello, first of all, thank you for creating this plugin, it helped me a lot for my theme.
I saw that version 0.1.3 was available, would it be possible to have this version in the zip file of the description?
https://github.com/ernilambar/ns-theme-check#option-1-easy
Thank you a lot.

**Comment by ernilambar** [comment]
Readme file https://github.com/WPTRT/ns-theme-check/blob/master/README.md is now updated with zip link of version `0.1.4`.

**Comment by oceanwp** [comment]
Hello, thank you but when I click on the Go button of the NS Theme Check page, there is a js error in the console:

Failed to load resource: the server responded with a status of 404 (Not Found) in /plugins/ns-theme-check/js/admin.js

I've the default theme and no other plugins activated.
Thank you :)

**Comment by ernilambar** [comment]
I checked the zip and it is working as expected. Is there file `admin.js` under `js` folder?

**Comment by oceanwp** [comment]
You're right, I just reinstall the plugin, it works perfectly, thanks :)
