### ISSUE TITLE
Travis build fails 

### ISSUE THREAD

**Issue by dingo-d** [WPTRT/ns-theme-check#34]
It seems to be failing on php v5.6 with `WP_VERSION=latest WP_MULTISITE=1 SNIFF=1`. 

When inspecting the job log I can see

~~~
The command "if [[ "$SNIFF" == "1" ]]; then phpcs --standard=phpcs.ruleset.xml $(find . -name '*.php'); fi" exited with 1.
~~~

Any idea why this happens?

**Comment by ernilambar** [comment]
Some ERRORS are there in the build details. Check https://travis-ci.org/ernilambar/ns-theme-check/jobs/218670432

**Comment by dingo-d** [comment]
Oh you mean like I need to fix the sniffs? Duh

**Comment by dingo-d** [comment]
This seems to be fixed with the new version.
