### ISSUE TITLE
Allow PR reviews

### ISSUE THREAD

**Issue by dingo-d** [WPTRT/ns-theme-check#46]
It would be a good thing if we could assign reviewers to PR's so that they are merged as soon as possible.

Thoughts? @ernilambar @grappler?

**Comment by grappler** [comment]
If you know of an option in GitHub to allow that I would be fine with activating it.

There are rarely PR that wait a long time otherwise you can ping me or @ernilambar in the PR.

10 hours response time is not too bad 😄

**Comment by dingo-d** [comment]
It's easier to tag someone to review it :D 

There should be a setting in the repo where the branches are to protect it, and there should be option to request a review before merging.

<img src="http://i.imgur.com/XNgtl9F.jpg"/>

**Comment by dingo-d** [comment]
@grappler if this has been solved, feel free to close the issue :)
