### ISSUE TITLE
Improving the ajax queue

### ISSUE THREAD

**Issue by grappler** [WPTRT/ns-theme-check#51]
I have made a few changes.
https://github.com/WPTRT/ns-theme-check/tree/feature/js-render-output

I have reverted back to using PHP to run the sniff instead of exec as that was not working well when zipping the files.

As the sniff is returning JSON, it is better for the JS to render the output instead of PHP.

Where I need help:
- When starting a check of a theme, the JS creates multiple ajax requests; one for each file in the theme. This could potentially slow down the browser if they are too many and the requests are still there after refreshing the page. It would be better for the next ajax call to be made one the previous one has completed.
- With the changes mentioned above, there is no proper message when the sniff fails and the ajax fails. Like I created for [in PHP a standard error](https://github.com/WPTRT/ns-theme-check/blob/master/inc/checks.php#L86-L110), we need to create one now in JS.

**Comment by dingo-d** [comment]
I can give this a look over the weekend. 

There shouldn't be a problem for starting a new ajax request only when the previous has ended - I usually add a class to a container in the `beforeSend` method and remove it on `complete`. That way you can wrap the entire ajax call in a conditional that checks if the class exists on a wrapper - if it exists, don't allow another one to be called.
Or we can have a flag at the beginning and then do a check in the `complete` method.

For the messages, we can localize those and then call them if fail happened via a localization object. 

This is what comes to my mind without looking at the code that much. I'll know more over the weekend.

**Comment by dingo-d** [comment]
Hi @grappler. I've made a PR for this (had some spare time on work) https://github.com/WPTRT/ns-theme-check/pull/52

I've looked at the error issue that you've mentioned. To have that we would need to differentiate inside `checks.php` between successful sniff and a failed sniff and send them to output. This way, the `$sniff` variable in `admin.php` would return a different data object, which we can also differentiate further to use either `wp_send_json_success( $sniff )` or `wp_send_json_error( $sniff )` that will be recognized in the js file, so that we can use the `renderJSON` function to display the error on front.

**Comment by grappler** [comment]
Thanks @dingo-d I will have a look at it.

The reason that your suggestion will not work as there are times where the sniff runs out of memory so you can't manipulate the result. The ajax just returns a 500 error status. So that is why we need to create a basic message object for when that happens.

**Comment by dingo-d** [comment]
Do you have a theme that does that so that I can test it?

**Comment by grappler** [comment]
Yes, the three.js file in https://wordpress.org/themes/three/

**Comment by dingo-d** [comment]
Will check it out!

**Comment by dingo-d** [comment]
I've added the fail message which displays on the front, the wording is the same as the one we've had before. Hope this is all ok.
